### ISSUE TITLE
Connection issues with MCP server

### ISSUE THREAD

**Issue by RonAutumn** [tumf/mcp-shell-server#1]
The MCP server is causing connection issues and needs to be removed or fixed. Users are receiving "Could not connect to MCP server" errors when trying to connect to this server.

**Comment by tumf** [comment]
please give me details. you can get the log here 
tail -n 120 -f ~/Library/Logs/Claude/mcp-server-shell.log

**Comment by hzj629206** [comment]
Also got error "Failed to start MCP server: Error in MCP connection to server shell: Error: spawn uvx ENOENT" when starting Claude app.

**Comment by hzj629206** [comment]
Can try to use the full path of `uvx` if it's installed in `$HOME/.local/bin`.
